  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mesop_sample_site_search:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mesop_sample_site_search:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'mesop_sample_site_search'
    - '--image'
    - 'gcr.io/$PROJECT_ID/mesop_sample_site_search:$COMMIT_SHA'
    - '--region'
    - 'europe-west4'
    - '--allow-unauthenticated'
  images:
  - 'gcr.io/$PROJECT_ID/mesop_sample_site_search:$COMMIT_SHA'
