  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/cloud-run/mesop:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/cloud-run/mesop:search:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'mesop'
    - '--image'
    - 'europe-west4-docker.pkg.dev/$PROJECT_ID/cloud-run/mesop:$COMMIT_SHA'
    - '--region'
    - 'europe-west4'
    - '--allow-unauthenticated'
  images:
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/cloud-run/mesop:$COMMIT_SHA'
  options:
    logging: CLOUD_LOGGING_ONLY
